### ISSUE TITLE
Setup dist serving through grunt of Angular app

### ISSUE THREAD

**Issue by totaldis** [yearography/core#4]
If you look at the Gruntfile.js it mentions kicking off the web app through a command like `grunt serve("dist")` 
Note the task:

``` js
grunt.registerTask('serve', 'Compile then start a connect web server', function (target) {
  if (target === 'dist') {
    return grunt.task.run(['build', 'connect:dist:keepalive']);
  }
```

The `build` task doesn't kick off things like autoreload on watched files, but does kick off things like uglify, htmlmin, etc...

Not sure if the grunt file takes care of dependencies, so may need to run these from the `/core/client` folder:

``` js
npm install
bower install
```

**Comment by jamie1911** [comment]
This wasn't fully resolved
